import type { Metadata } from "next";
import { Titillium_Web, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Titillium_Web({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: "200",
});

const geistMono = Poppins({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  weight: "200",
});

export const metadata: Metadata = {
  title: "stock dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
